name: continuous-integration

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - '**/*.md'
      - '.gitlab-ci.yml'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'FILE_TEMPLATE'
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.*           # i.e. v1.0, v2.1rc1
    tags:
      - v*
    paths-ignore:
      - '**/*.md'
      - '.gitlab-ci.yml'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'FILE_TEMPLATE'

env:
  IMAGE: paritytech/ci-unified:bullseye-1.71.0-v20230727

jobs:
  set-image:
    # GitHub Actions does not allow using 'env' in a container context.
    # This workaround sets the container image for each job using 'set-image' job output.
    runs-on: ubuntu-latest
    outputs:
      IMAGE: ${{ steps.set_image.outputs.IMAGE }}
    steps:
      - id: set_image
        run: echo "IMAGE=${{ env.IMAGE }}" >> $GITHUB_OUTPUT

# lint
  lint:
    runs-on: ubuntu-latest
    needs: [set-image]
    container:
      image: ${{ needs.set-image.outputs.IMAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: fmt
        run: |
          time cargo +nightly fmt --all -- --check

      - name: Clippy
        run: |
          time cargo clippy --all-targets -- -D warnings

      - name: Check
        run:
          time cargo check --all-targets --workspace

# # test
  test:
    runs-on: ubuntu-latest
    needs: [set-image]
    container:
      image: ${{ needs.set-image.outputs.IMAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Test
        run: |
          rustup show
          cargo --version
          rustup +nightly show
          cargo +nightly --version
          bash --version
          ./scripts/ci/zombienet/zombie.sh setup
          ZOMBIE_WS_PORT=9900 ./scripts/ci/zombienet/zombie.sh run ./scripts/ci/zombienet/network.toml
          WS_URL=ws://127.0.0.1:9900 time cargo test --all-targets --workspace
          ./scripts/ci/zombienet/zombie.sh shutdown

# # build
  build:
    runs-on: ubuntu-latest
    needs: [set-image, test]
    container:
      image: ${{ needs.set-image.outputs.IMAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build
        run: |
          time cargo build --release

      - name: Archive aritfacts
        uses: actions/upload-artifact@v3
        with:
          name: polkadot-introspector
          path: |
            target/release/polkadot-block-time
            target/release/polkadot-jaeger
            target/release/polkadot-kvdb
            target/release/polkadot-parachain-tracer
            target/release/polkadot-whois
          retention-days: 1


  build-docker:
    runs-on: ubuntu-latest
    needs: [set-image, build]
    # container:
    #   image: ${{ needs.set-image.outputs.IMAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: polkadot-introspector
          path: artifacts

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          file: ./scripts/ci/dockerfiles/polkadot-introspector_injected.Dockerfile
          build-args: |
            VCS_REF="${CI_COMMIT_SHA}"
            build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
          tags: latest

      - name: Check image
        run: |
          docker images


# # publish
#   publish-docker:

#   publish-docker-image-description: